version: '3'

services:
  app:
    container_name: docker-app
    image: node:17.6.0
    working_dir: /home/node/app
    command: "sh -c 'npm install && npm run build && npm run start:prod'"
    user: "node"
    volumes:
      - ./app:/home/node/app
    networks:
      - docker-network

  db:
    image: postgres:14.1-alpine
    container_name: docker-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    networks:
      - docker-network

  nginx:
    image: nginx:stable-alpine
    container_name: docker-nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - app
      - db
    networks:
      - docker-network


volumes:
  postgres_db:

networks:
  docker-network:
    driver: bridge
