version: '3'

services:
  frontend:
    container_name: salary-frontend
    image: node:17.6.0
    working_dir: /home/node/app
    command: "sh -c 'yarn && yarn build && yarn start'"
    user: "node"
    volumes:
      - ./frontend:/home/node/app
    networks:
      - salary-network

  app:
    container_name: salary-app
    image: node:17.6.0
    working_dir: /home/node/app
    command: "sh -c 'yarn && yarn build && yarn start:prod'"
    user: "node"
    ports:
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
    networks:
      - salary-network

  db:
    image: postgres:14.1-alpine
    container_name: salary-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    networks:
      - salary-network

  nginx:
    image: nginx:stable-alpine
    container_name: salary-nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - app
      - db
    networks:
      - salary-network


volumes:
  postgres_db:

networks:
  salary-network:
    driver: bridge
