version: "3"

services:
  frontend:
    command: "sh -c 'yarn && yarn dev'"
  app:
    command: "sh -c 'yarn && yarn start:debug'"
  nginx:
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf